version: "3.8"

services:
  electron-mcp-server:
    build: .
    container_name: electron-mcp-server
    restart: unless-stopped
    volumes:
      # Mount host directories for Electron projects
      - ./projects:/app/projects
      # Mount screenshots directory
      - ./screenshots:/app/screenshots
    environment:
      - NODE_ENV=production
      - DISPLAY=:99
    # For X11 forwarding if needed
    # volumes:
    #   - /tmp/.X11-unix:/tmp/.X11-unix:rw
    # environment:
    #   - DISPLAY=${DISPLAY}
    # network_mode: host

  # Optional: VS Code server for development
  vscode-server:
    image: codercom/code-server:latest
    container_name: electron-mcp-vscode
    ports:
      - "8080:8080"
    volumes:
      - .:/home/coder/workspace
      - ~/.config/code-server:/home/coder/.config/code-server
    environment:
      - PASSWORD=electron-mcp-dev
    command: --bind-addr 0.0.0.0:8080 --auth password /home/coder/workspace
    depends_on:
      - electron-mcp-server
